### ISSUE TITLE
Indexed Meshes

### ISSUE THREAD

**Issue by tay10r** [madmann91/bvh#11]
Are they not supported? I use indexed meshes because it's faster applying transformations to them. The difficulty is that this library seems to require that each primitive is an instanced class.

Specifically, it's arranged like this.

```cxx
template <typename Float, typename Index>
struct Mesh final {
  Eigen::Matrix<Float, 3, Eigen::Dynamic> vertices;
  Eigen::Matrix<Float, 3, Eigen::Dynamic> normals;
  Eigen::Matrix<Float, 2, Eigen::Dynamic> tex_coords;

  /* +3 vertices, +3 normals, +3 texture coordinates */
  Eigen::Matrix<Index, 9, Eigen::Dynamic> faces;
};
```
I don't think this is too uncommon, it's how [libigl](https://libigl.github.io/) seems to handle meshes as well.

**Comment by madmann91** [comment]
It does support indexed meshes. The intersection and traversal are vastly faster by not using an indexed representation and removing indirections. You could create a [custom intersector](https://github.com/madmann91/bvh/blob/master/test/custom_intersector.cpp) that does indirections to look up the triangle but I strongly recommend against it, as the performance it is 20-30% if not more, depending on your layout.

**Comment by madmann91** [comment]
Also, during construction, having a centers and bounding box for each primitive is necessary to have an acceptable performance at all. At each level of the BVH, the center and bounding box of every primitive will be re-evaluated, so in this case if this library were to do indirections and recompute centers and bounding boxes, construction algorithms would be several _times_ slower.

**Comment by tay10r** [comment]
I guess the hit on transforms is just inevitable then. Alright, thanks for the advice!
