### ISSUE TITLE
no intersection in some cases when there is a -0.0 direction value

### ISSUE THREAD

**Issue by alexf539** [madmann91/bvh#20]
Hi,
there seems to be a problem when there is a -0.0 value in the direction vector. I slightly modified your example from simple_example.cpp to reproduce this error:

I just copied the first triangle and moved it a bit further away (in the z-direction) and also changed the origin of the ray so that there should be a clear intersection:

```
    std::vector<Triangle> triangles;
    triangles.emplace_back(
        Vector3( 1.0, -1.0, 1.0),
        Vector3( 1.0,  1.0, 1.0),
        Vector3(-1.0,  1.0, 1.0)
    );
    triangles.emplace_back(
        Vector3( 1.0, -1.0, 2.1),
        Vector3( 1.0,  1.0, 2.1),
        Vector3(-1.0,  1.0, 2.1)
    );

    // Version 1: hit: triangle:0, distance:1, u:0.25, v:0.375
    Ray ray(
        Vector3(0.25, 0.25, 0.0),
        Vector3(0.0, 0.0, 1.0), 
        0.0,
        100.0
    );

    // Version 2: no hit
    Ray ray2(
        Vector3(0.25, 0.25, 0.0),
        Vector3(0.0, -0.0, 1.0), 
        0.0,
        100.0
    );
```
But there is still a hit in the second version when the second triangle is at z=2.0. I also tried `RobustNodeIntersector`, but with no luck :/

**Comment by madmann91** [comment]
I'm going to look into this. It is indeed a bug in the node intersector.

**Comment by madmann91** [comment]
This issue should now be resolved after the recent commits. Thank you for the bug report!

**Comment by alexf539** [comment]
Yep, it is fixed now. Thanks!
