### ISSUE TITLE
MSVC bit field packing

### ISSUE THREAD

**Issue by RNuWM** [madmann91/bvh#24]
Bit field packing is implementation dependent. Unfortunately, you could argue MSVC is not as smart as GCC (or whatever you developed for) in terms of packing: https://docs.microsoft.com/en-us/cpp/cpp/cpp-bit-fields?redirectedfrom=MSDN&view=msvc-160

For instance, sizeof(Bvh<double>::Node) ends up at 72 instead of 64 bytes because the packed in bool effectively becomes an unpacked IndexType. Switching to a uniform type across the bit fields will fix the issue:

`IndexType  is_leaf : 1;`
`IndexType primitive_count : sizeof(IndexType) * CHAR_BIT - 1;`
`IndexType first_child_or_primitive;`

Obviously has the draw back of losing the explicit bool type. There may be another way to get the desired packing out of MSVC, but I am not aware of it.

Not sure if/how you want to handle this, so didn't do a PR.

**Comment by madmann91** [comment]
Hello, and thank you for the bug report! I am a bit surprised at this result here, as I would expect any decent compiler to do the right thing for this very simple task. I would consider this a bug in MSVC and in any case I suggest that you report it to the MSVC developers as a performance bug. I will work on a fix in the mean time.

**Comment by madmann91** [comment]
This should be fixed in 4affa36. The leaf flag is no longer needed since nodes that have `primitive_count > 0` are now considered leaves.

**Comment by madmann91** [comment]
As a consequence of this change, BVHs with no primitives are no longer supported. I have placed assertions in all of the builders (some already did not support empty BVHs).
