### ISSUE TITLE
LocallyOrderedClustering does not terminate

### ISSUE THREAD

**Issue by Janos95** [madmann91/bvh#29]
Unfortunately the LocallyOrderedClustering does not terminate with the lucy 3D model, maybe some race condition?! I am on Linux with gcc 10.2. I'll will debug this a bit more, but in case you want to try to reproduce, I have uploaded a minimal reproducer [here](https://github.com/Janos95/bvh_bench).

**Comment by madmann91** [comment]
Thank you for the bug report. I'll look into it.

**Comment by madmann91** [comment]
Probably unrelated but you'll get better trees by using the primitive centers rather than the bounding box centers.

**Comment by madmann91** [comment]
Also it does not seem to hang. It just merges only a few nodes per iteration, which is not expected at all. Running with `OMP_NUM_THREADS=1 ./bench` does not remove the problem so it's not a race condition.

**Comment by Janos95** [comment]
Right, good point should've tried without OpenMP myself. I just ran it for like 15 minutes, so I just assumed it was hanging, sorry for being hasty!

**Comment by madmann91** [comment]
No problem. Also it seems you never compute the global bounding box. You can actually use `bvh::compute_bounding_boxes_union()` for this.

**Comment by madmann91** [comment]
So with the following corrected code:
```cpp
std::vector<BoundingBox> bboxes(tCount);                                                                                                                              
std::vector<Vector3> centers(tCount);

#pragma omp parallel for
for(size_t i = 0; i < tCount; ++i) { 
    uint32_t a = indices[i][0],b = indices[i][1],c = indices[i][2];
    auto v0 = Vector3(pos[a][0], pos[a][1], pos[a][2]);
    auto v1 = Vector3(pos[b][0], pos[b][1], pos[b][2]);
    auto v2 = Vector3(pos[c][0], pos[c][1], pos[c][2]);
    centers[i] = (v0 + v1 + v2) * (Scalar(1.0) / Scalar(3.0));
    bboxes[i] = BoundingBox(v0).extend(v1).extend(v2);
} 
auto global_bbox = bvh::compute_bounding_boxes_union(bboxes.data(), bboxes.size());
```
Your program now works. As a side note, it seems some primitives are literally just points (their bounding box has 0 volume), so I suppose some thing is broken in the library you use to import your model, or maybe in the model itself. In any case, the library you use to load your models is extremely inefficient since it uses `std::vector<std::vector<uint32_t>>` to represent triangles.

**Comment by Janos95** [comment]
Yes, can confirm this works! Ok, so not surprisingly, it was my mistake :laughing: , thanks for the help.

The mesh is a 3D scan, so thats why its not super clean, I don't think its because of the importer.
Yeah, I know the importer is not great, in fact it is 7x slower than the importer I was actually using, but
for the minimal example used this one since its a single header. If you know a fast ply importer than
can be dropped into one's project, I am keen to know about it :)
