### ISSUE TITLE
Other traversal types

### ISSUE THREAD

**Issue by madmann91** [madmann91/bvh#30]
As it stands now, there's only one traversal algorithm. I'd like to implement the following algorithms:
- A frustum-based ray traversal algorithm,
- A aligned/oriented bounding-box intersection algorithm,
- A BVH/BVH intersection algorithm.
- Closest point detection.

**Comment by OptimisticMonkey** [comment]
An aabb intersection algorithm that returned all hits would be a great addition ;-)

**Comment by madmann91** [comment]
See my answer to issue #33
