### ISSUE TITLE
Dot Product Elimination in Sphere Intersector

### ISSUE THREAD

**Issue by tay10r** [madmann91/bvh#37]
https://github.com/madmann91/bvh/blob/fac27c6a30520426d0d52164563bf607258d3d16/include/bvh/sphere.hpp#L42

I believe there's a potential optimization here. If you assume the ray direction is normalized, the length of the vector will always equal `1`.  Since `sqrt(1)` is always `1`, you can probably just leave it as:

```cpp
const Scalar a = 1;
```

Embree still takes the dot product, perhaps because they don't assume the ray direction is normalized. Since there's some template magic at work here, you could probably do something like:

```cpp
template <typename Scalar, bool NormalizedRayDir>
struct Sphere final {
  /* ... */
  static Scalar get_ray_direction_squared_length(const Ray<Scalar> &ray);
};

template <typename Scalar>
Scalar Sphere<Scalar, true>::get_ray_direction_squared_length(const Ray<Scalar>&)
{
  return 1;
}

template <typename Scalar>
Scalar Sphere<Scalar, false>::get_ray_direction_squared_length(const Ray<Scalar>& ray)
{
  return dot(ray.direction, ray.direction);
}
```

Maybe it would also do well as a template parameter for `Ray` instead, hard to say.

**Comment by madmann91** [comment]
Implemented in commit bc3eff9.
