### ISSUE TITLE
global bounding box does not seem to work

### ISSUE THREAD

**Issue by AODQ** [madmann91/bvh#4]
Hey, so ever since commit d2f5e2f0b8dc863160496a972c912f5d2736d4d8 , which added the global bounding box, my renderer does not seem to render anything under the same scene/camera settings. I'm using `bvh::compute_bounding_boxes_union`, yet despite this, I can't get it to properly intersect with any triangle.

```
  auto globalBbox =
    bvh::compute_bounding_boxes_union(
      boundingBoxes.data()
    , self->triangles.size()
    );

  { // -- build tree
    bvh::BinnedSahBuilder<decltype(self->boundingVolume), 32>
      boundingVolumeBuilder { self->boundingVolume };

    boundingVolumeBuilder.build(
      globalBbox, boundingBoxes.data(), centers.data(), self->triangles.size()
    );
  }
```
This code works (without globalBbox references) before the aforementioned commit. Let me know if I'm doing something wrong here.

**Comment by AODQ** [comment]
By the way, possibly related, but ever since that commit, bvh::SweepSahBuilder crashes when trying to use it to build. I'm assuming it is related to this issue.

**Comment by madmann91** [comment]
Hello, and thank you for the report. I'll have a look.

**Comment by madmann91** [comment]
I managed to build your project ([AODQ/cpu-raytracer](https://github.com/AODQ/cpu-raytracer), I suppose), but I cannot seem to run it at all. It just gives me the error:

```
~/P/c/build> ./cpuraytracer -f ../../bench_scenes/kitchen/kitchen.obj
Argument ‘
Aborting (exceptions disabled)...
fish: Job 2, “./cpuraytracer -f ../../bench_s…” terminated by signal SIGABRT (Abort)
```

**Comment by AODQ** [comment]
@madmann91 Hey, thanks! I haven't updated it to use your most recent dependency, I'll go ahead and do that when I get home.

**Comment by madmann91** [comment]
Also note that `bvh::shuffle_primitives` now _returns_ the new shuffled array instead of modifying the argument.

**Comment by AODQ** [comment]
@madmann91 ; ah , that is exactly what was occurring, I had not noticed that change. Thank you. And yes `bvh::SweepSahBuilder` works now
