### ISSUE TITLE
raw, bvh node data to upload to the gpu

### ISSUE THREAD

**Issue by sivansh11** [madmann91/bvh#53]
I am currently workin on a raytrcer in opengl, do ou have a api to get the raw bvh node data (and any other essential data) to be uploaded to the gpu as a ssbo ?

**Comment by madmann91** [comment]
For a `Bvh bvh`, the node data is simply `bvh.nodes.get()`. For indices, use `bvh.indices.get()`. There are no pointers, only indices, so it is suitable to use directly without any other operation. The BVH only holds the node count, the index count is a client-provided piece of information, so it is not kept in the BVH (there are as many indices as there are primitives in the BVH). Please re-open if that does not answer your question.
