### ISSUE TITLE
`build()` in debug build of v2 feels slower than v1

### ISSUE THREAD

**Issue by tksuoran** [madmann91/bvh#54]
When I updated my code to use v2, I feel that `build()` in debug build got slower.
Is there anything I could do to make `build()` faster in debug builds? I am already using low quality setting for the default builder. Thanks!

**Comment by madmann91** [comment]
You could try disabling assertions, by defining `-DNDEBUG` in your debug build, or locally in the header or sources files, by using `#define NDEBUG` **before** including any file from this library. Let me know if this helps (or not).

**Comment by tksuoran** [comment]
I ended up caching BVHs into filesystem, using `serialize.cpp` for reference and using fnv-1a hash from triangle corner coordinates as file name. Seems to work for me :)
