### ISSUE TITLE
Face culling options?

### ISSUE THREAD

**Issue by fynv** [madmann91/bvh#56]
Are there face culling options in bvh? It seems to me that a ray can intersect a triangle no matter which direction it comes from.
I hope there can be options to skip triangles based on their winding directions. Is that easy to do?
Thanks.

**Comment by madmann91** [comment]
You can do that by hacking into `PrecomputedTri` and having an early check that `dot(ray.dir, n)` is >0 or <0 (depending on whether you want to cull back- or front-faces). Note that performance is not guaranteed to increase with culling. In fact, it may even decrease, as sometimes culling triangles might result in other, expensive parts of the geometry becoming visible. If you feel adding this to the library would be worthwhile, you can create a PR and I will review it.
