### ISSUE TITLE
Identifiers near and far in bvh.h cause issues when precompiled headers are used

### ISSUE THREAD

**Issue by tksuoran** [madmann91/bvh#61]
I am trying to enable use of precompiled headers in my project which uses bvh. Using PCH seems to cause MSVC compiler have issues with identifiers `near` and `far` in `bvh.h`. I wonder if these could be modified in order to avoid the issue? Thanks.

**Comment by madmann91** [comment]
Hello! I believe those issues come from the fact that `windef.h` defines `near` and `far`. Would it be possible to not include those files (directly or indirectly) before including anything from this library? Alternatively, it should be possible to simply do:
```cpp
#undef near
#undef far
```
If this does not fix the problem for some reason, please comment below.

**Comment by tksuoran** [comment]
I got it working. Thanks!

**Comment by mrzade** [comment]
With an unscoped undef of these two macros,  you're risking breaking the rest of the Windows code.
