### ISSUE TITLE
config.min_leaf_size > 1 Leads to assertion failure

### ISSUE THREAD

**Issue by nkallen** [madmann91/bvh#65]
https://github.com/madmann91/bvh/blob/ad3d4361b77090a72aff4aa7edae3a0806645165/src/bvh/v2/mini_tree_builder.h#L285

Hi, 

I'm still exploring the library so apologies if I'm doing something stupid. I'm primarily interested in fast "picking" and frustum intersection for box selection. So I was looking into using less memory (at the cost of more cpu) by setting config.min_leaf_size = 8, but it lead to an assertion error.

Thanks

**Comment by madmann91** [comment]
Hello, and thank you for your interest. I believe this is due to the fact that, with the mini-tree builder, the top-level tree must be built with `min_leaf_size == 1`. I have pushed a fix (02ee929) on master.
