### ISSUE TITLE
What is the use case? is it slower than embree?

### ISSUE THREAD

**Issue by dungeon2567** [madmann91/bvh#66]

**Comment by madmann91** [comment]
See the documentation. It's around 20-30% slower than Embree to trace rays with, on the hardware I used to benchmark. YMMV.

Here are some uses cases for this library:

- When you need lower access to the BVH than what Embree provides (e.g. writing a GPU raytracer),
- When you need something small, header-only,
- When you need to run ray-traversal on non-x86 architectures (the code is portable and does not use any architecture- or platform-specific intrinsic),
- When you want to have 2D, 4D, or arbitrary dimension BVHs,
- When you want to learn about implementing BVHs in an efficient way, without having to lookup the complex code in Embree (the code is rather straightforward -- the binned builder for instance is around 150 lines of code).
