### ISSUE TITLE
CMake Version

### ISSUE THREAD

**Issue by tay10r** [madmann91/bvh#7]
I noticed that the CMake version got bumped up again to version 3.13.5
This breaks the build for anyone who has the standard distribution of CMake on the latest Ubuntu (19.10), which is CMake version 3.13.4.

Was this bumped up because of `target_link_options`? That's supported by 3.13.4, even though the documentation doesn't specify it.

It might also make the Travis build simpler, since you won't have to install a new CMake version.

**Comment by madmann91** [comment]
Unfortunately, on Travis CI (bionic) the CMake version is still 3.12.4. I did downgrade to 3.13 in d57782f, though, which is the first version to support `target_link_options`.

**Comment by jeffamstutz** [comment]
Is there a reason to not use the CMake `OpenMP::OpenMP_CXX` target instead of manually setting all the interface options by hand? The target was initially defined by CMake 3.9 and avoids the need for `target_link_options`.

Example here: https://github.com/jeffamstutz/bvh/blob/master/CMakeLists.txt

**Comment by jeffamstutz** [comment]
I could make a quick PR if the downgrade to CMake 3.9 minimum doesn't create any issues anywhere else.
