### ISSUE TITLE
Adding and Removing elements

### ISSUE THREAD

**Issue by heyx3** [madmann91/bvh#76]
I'd like to use this library for something more akin to collision/nearest neighbors detection rather than ray-tracing. But this would require a bit more dynamism. I propose adding at least a `DefaultAdder`, `DefaultRemover`, and maybe even `DefaultUpdater`, possibly with alternative versions; in the style of `DefaultBuilder` and its alternatives. Adding and removing elements dynamically while maintaining a good tree is a hard problem I'm sure, but even a simplistic implementation would be nicer than having to roll a bad implementation myself.

**Comment by madmann91** [comment]
Just add your nodes to the root and run the reinsertion optimizer. This should work all the time and produce decent trees. If for some reason this does not work for you then re-open this issue and explain the nature of the problem.
