### ISSUE TITLE
Updating node positions and sizes?

### ISSUE THREAD

**Issue by kariem2k** [madmann91/bvh#85]
Hello,

Thank you for the library, I am trying to use it for a strategy game. But I don't know how to update node positions and scaling. Do I need to rebuild the dynamic object tree(s) every time they mode and do I remove this tree and reinsert it in a bigger tree? 

Thank you

**Comment by madmann91** [comment]
You have two options:
1. Rebuild from scratch at every change,
2. Place insert the node at the root and optimize the BVH

The first method should be easy enough to implement. The second can be implemented by adding one node `R'` that encompasses both the previous root `R` and the object `O` to add:

```
   R'
 /   \
O     R
```

Then, you can run the reinsertion optimizer on the tree, which should balance it such that the structure of the tree is more efficient for ray-tracing.

**Comment by madmann91** [comment]
Note that to add a node, you don't have to shift all the nodes in the tree, you can simply add an element at the end of the array of nodes, copy the previous root into it, and overwrite the actual root (which always is located at index 0) have it as its left or right child.

**Comment by kariem2k** [comment]
Thank you very much
