### ISSUE TITLE
box collision detection

### ISSUE THREAD

**Issue by wangkeke1800** [madmann91/bvh#90]
this BVH can be used for ray tracing, how to use it for AABB  bounding box collision detection, Detect objects around the specified AABB bounding box.

**Comment by madmann91** [comment]
There is only little support for intersecting this BVH with something else than rays. In particular, you can use the `traverse_top_down` method of the `Bvh` structure (https://github.com/madmann91/bvh/blob/master/src/bvh/v2/bvh.h#L65). You can plug any node intersection/leaf intersection code in there, which should be easy enough to write down if you have aligned bounding boxes.

```cpp
SmallStack<Bvh::Index, stack_size> stack;
auto intersect_nodes = [] (Node& left, Node& right) {
  bool hit_right = ...;   // Whether the right child was intersected or not
  bool hit_left = ...;    // Whether the left child was intersected or not
  bool should_swap = ...; // Whether to intersect the right child first instead of the left one first
  return std::make_tuple(hit_left, hit_right, should_swap);
};
auto intersect_leaf = [&] (size_t begin, size_t end) {
  for (size_t i = begin; i < end; ++i) {
    size_t prim_id = bvh.prim_ids[i];
    // Intersect primitive located at index `prim_id`
  }
};
bvh.traverse_top_down(bvh.get_root(), stack, intersect_leaf, intersect_nodes);
```
