### ISSUE TITLE
aboult add remove or modify operation

### ISSUE THREAD

**Issue by LiangLin0316** [madmann91/bvh#94]
Could the author support adding, removing, or updating box nodes in an already built BVH tree without needing to rebuild the entire tree each time? Rebuilding the entire tree every time should be more time-consuming than modifying an existing tree, right?

**Comment by madmann91** [comment]
There is unfortunately no canonical way to add or remove nodes in a BVH. One option is to add two nodes at the end of the array, move the root of the BVH to one of them and the node to insert in the other, and then enlarge the root node to fit the previous root and the added node. To give an example, this simple method would work like this:

1.Initial BVH
```
  A
 / \
B   C

In memory: [A, B, C]
```
2. Adding node D:
```
    R
   / \
  A   D
 / \
B   C

In memory: [R, B, C, A, D]
```

This method is simple and easy to implement, but it produces bad BVHs: First, the root node now jumps to another node, very far from it, which is not good for cache coherence during traversal, and second, the structure of the BVH is probably not optimal from a traversal cost point of view.

The method I would recommend for someone who doesn't understand/know the tradeoffs of working with BVHs, is to implement this method, then run the re-insertion optimizer. See issue #76.
